// Regenerate the leaderboard block in README.md from data/.
//
// A stale leaderboard in the README of a leaderboard is the worst failure this repo
// has available, so the table is never hand-edited: build.sh rewrites it between the
// markers below on every build.
import fs from "node:fs";
import { perSiteDivisor, perSiteLabel, isSampled } from "./units.mjs";
import { collect, recordOf, summarize } from "./summary.mjs";

const BEGIN = "<!-- BEGIN LEADERBOARD (generated by scripts/readme_table.mjs - do not edit) -->";
const END = "<!-- END LEADERBOARD -->";

// Curated, not top-N-by-anything. These are the instances the field competes on; an
// automatic ranking by V-score surfaces the stale J2 != 0.5 baselines instead and
// buries 10x10. The internal view of those is scripts/staleness.mjs.
const FRONTIER = [
  ["J1J2/square_64_P_0.5", "J1-J2 square 8x8, J2 = 0.5"],
  ["J1J2/square_100_P_0.5", "J1-J2 square 10x10, J2 = 0.5"],
  ["J1J2/square_256_P_0.5", "J1-J2 square 16x16, J2 = 0.5"],
  ["J1J2/square_400_P_0.5", "J1-J2 square 20x20, J2 = 0.5"],
  ["Hubbard/square_256_P_112_8", "Hubbard square 16x16, U = 8, n = 0.875"],
  ["Hubbard/rectangular-4x16_64_P_28_8", "Hubbard 4x16, U = 8, n = 0.875"],
  ["Heisenberg/triangular_196_O", "Triangular Heisenberg, 196 sites, open"],
  ["Heisenberg/kagome-8x8_192_P", "Kagome Heisenberg, 192 sites"],
  ["Heisenberg/pyrochlore-4x4x4_256_P", "Pyrochlore Heisenberg, 256 sites"],
];

// Physics convention: one significant digit of uncertainty in parentheses, and the
// energy quoted to exactly that decimal place. Quoting digits past the error bar is
// how a table invents precision nobody claimed.
function quote(energy, sigma) {
  if (sigma == null) return { text: energy.toFixed(7), decimals: 7 };
  const rounded = Number(sigma.toPrecision(1));
  const decimals = Math.max(0, -Math.floor(Math.log10(rounded)));
  const digit = Math.round(rounded * 10 ** decimals);
  return { text: `${energy.toFixed(decimals)}(${digit})`, decimals };
}

// Method strings run to 60+ characters and would otherwise be cut mid-word, which
// reads as a typo rather than as an abbreviation.
function shorten(method, max) {
  if (method.length <= max) return method;
  const cut = method.slice(0, max);
  const at = Math.max(cut.lastIndexOf(" "), cut.lastIndexOf(","));
  return (at > max * 0.6 ? cut.slice(0, at) : cut).replace(/[,(]$/, "") + "...";
}

// arXiv id or journal DOI, whichever the reference carries. Imported VarBench rows
// store markdown links; rows we added store a citation string.
function sourceCell(ref) {
  const arxiv = ref.match(/arxiv\.org\/abs\/([\d.]+)|arXiv:([\d.]+)/i);
  if (arxiv) {
    const id = arxiv[1] || arxiv[2];
    return `[arXiv:${id}](https://arxiv.org/abs/${id})`;
  }
  const paper = ref.match(/\[paper\]\((https?:\/\/[^\s)]+)\)/);
  if (paper) return `[paper](${paper[1]})`;
  const code = ref.match(/\[code\]\((https?:\/\/[^\s)]+)\)/);
  if (code) return `[code](${code[1]})`;
  return ref.slice(0, 40) || "n/a";
}

const instances = collect();
const byId = new Map(instances.map(i => [i.instance_id, i]));
const s = summarize(instances);

const lines = [];
lines.push("| instance | rows | record | method | source | closest challenger |");
lines.push("|---|---:|---|---|---|---|");

for (const [id, label] of FRONTIER) {
  const inst = byId.get(id);
  if (!inst) throw new Error(`FRONTIER names ${id}, which is not in data/`);
  const f = perSiteDivisor(inst) ?? 1;
  const rec = recordOf(inst);
  if (!rec) {
    lines.push(`| ${label} | ${inst.rows.length} | no record | | | |`);
    continue;
  }
  const q = quote(rec.energy / f, rec.sigma == null ? null : rec.sigma / f);
  const sorted = [...inst.rows].sort((a, b) => a.energy - b.energy);
  const next = sorted
    .slice(sorted.indexOf(rec) + 1)
    .find(r => r.bound_type === "variational" && !r.defect);
  // Quoted at the record's precision so the two are readable against each other. The
  // dagger marks a sampled energy with no stated error bar: listed, but eligible for
  // nothing (RULES.md 6). A deterministic row needs no sigma and gets no dagger.
  const challenger = next
    ? `${(next.energy / f).toFixed(q.decimals)}${isSampled(next.method) && next.sigma == null ? " &dagger;" : ""} ${shorten(next.method, 34)}`
    : "none";
  lines.push(`| ${label} | ${inst.rows.length} | **${q.text}** | ${shorten(rec.method, 46)} | ${sourceCell(rec.reference)} | ${challenger} |`);
}

const spin = perSiteLabel(byId.get("J1J2/square_100_P_0.5"));
const site = perSiteLabel(byId.get("Hubbard/square_256_P_112_8"));
lines.push("");
lines.push(`Energies are per site: spin models as \`${spin}\`, Hubbard as \`${site}\` (see`);
lines.push("[units and conventions](#units-and-conventions)). **Bold** is the record under");
lines.push("[the ranking rules](#how-the-ranking-works); &dagger; marks a sampled energy with no stated");
lines.push("error bar, which is listed but cannot hold a record.");
lines.push("");
const b = s.blocked_on_sigma;
lines.push(`Across the whole table: **${s.records.held} of ${s.instances} instances have a record**, from ${s.rows} rows.`);
lines.push(`Of the ${s.instances - s.records.held} instances without one, ${s.records.none_exact_only} are solved exactly and have nothing to compete`);
lines.push(`for. Separately, **${b.rows} sampled variational rows across ${b.instances} instances carry no error bar**, so`);
lines.push(`they are listed and rank for nothing — and ${b.would_take_record} of them sit below their instance's current`);
lines.push("record. If one of those is your paper, the error bar is the only thing missing.");

const readme = fs.readFileSync("README.md", "utf8");
const i = readme.indexOf(BEGIN);
const j = readme.indexOf(END);
if (i < 0 || j < 0) throw new Error("README.md is missing the leaderboard markers");
// Spliced by index, never by String.replace: a replacement containing $' or $& is
// interpreted as a match reference and pastes the file back into itself.
const block = `${BEGIN}\n\n${lines.join("\n")}\n\n${END}`;
fs.writeFileSync("README.md", readme.slice(0, i) + block + readme.slice(j + END.length));
console.log(`README.md leaderboard: ${FRONTIER.length} instances, ${s.records.held}/${s.instances} records held`);
