// Regenerate the leaderboard block in README.md from data/.
//
// A stale leaderboard in the README of a leaderboard is the worst failure this repo
// has available, so the table is never hand-edited: build.sh rewrites it between the
// markers below on every build.
// The instance labels, the quoting convention and the no-record reasons are exported
// because the site (site.mjs) renders the same table in HTML. Two copies of "how an
// instance is named" would drift, and the drift would be invisible until someone
// compared the README against the front page.
import fs from "node:fs";
import path from "node:path";
import { perSiteDivisor, perSiteLabel, isSampled, noErrorMetrics } from "./units.mjs";
import { collect, recordOf, summarize, noRecordKey } from "./summary.mjs";
import { citeCell } from "./cite.mjs";
import { sources } from "./enrich_sources.mjs";

const BEGIN = "<!-- BEGIN LEADERBOARD (generated by scripts/readme_table.mjs - do not edit) -->";
const END = "<!-- END LEADERBOARD -->";

// Physics convention: one significant digit of uncertainty in parentheses, and the
// energy quoted to exactly that decimal place. Quoting digits past the error bar is
// how a table invents precision nobody claimed.
export function quote(energy, sigma) {
  // A stated sigma of exactly 0 is how the upstream tables write "deterministic" on an
  // exact diagonalization. There is no last digit for it to qualify, and taking its
  // logarithm asks for infinitely many decimals, so it is quoted like a row with none.
  if (sigma == null || !(sigma > 0)) return { text: energy.toFixed(7), decimals: 7 };
  const rounded = Number(sigma.toPrecision(1));
  const decimals = Math.max(0, -Math.floor(Math.log10(rounded)));
  const digit = Math.round(rounded * 10 ** decimals);
  return { text: `${energy.toFixed(decimals)}(${digit})`, decimals };
}

// Method strings run to 60+ characters and would otherwise be cut mid-word, which
// reads as a typo rather than as an abbreviation.
export function shorten(method, max) {
  if (method.length <= max) return method;
  const cut = method.slice(0, max);
  const at = Math.max(cut.lastIndexOf(" "), cut.lastIndexOf(","));
  return (at > max * 0.6 ? cut.slice(0, at) : cut).replace(/[,(]$/, "") + "...";
}

// Markers shown against a number, in precedence order. A row carrying no error metric
// at all gets the circle and nothing else - the dagger would be redundant, since a
// sampled row with no variance has no sigma either.
export function marks(r) {
  if (noErrorMetrics(r)) return " &#9675;";
  if (isSampled(r.method) && r.sigma == null) return " &dagger;";
  return "";
}

// Every instance is listed, one collapsed table per model, and the reader clicks through
// them; the frontier table (views.mjs) is rendered only on the site. Those labels are built
// from the instance itself, so anything added to data/ appears without a hand-written entry.
export const MODELS = [
  ["Heisenberg", "Heisenberg"],
  ["J1J2", "J1-J2"],
  ["Hubbard", "Hubbard"],
  ["tV", "Spinless t-V"],
  ["TFIsing", "Transverse-field Ising"],
  ["Impurity", "Impurity"],
];

// Boundary codes as defined in vendor/varbench/lattice.md. Periodic is the default and
// goes unsaid, as in the frontier labels.
export const BOUNDARY = { O: "open", PO: "periodic/open", PA: "periodic/antiperiodic" };

export function geometry(inst) {
  const n = inst.n_sites;
  const cells = inst.lattice.match(/^([a-z]+)-(\d+(?:x\d+)+)$/);
  if (cells) {
    const product = cells[2].split("x").reduce((a, b) => a * Number(b), 1);
    return product === n ? `${cells[1]} ${cells[2]}` : `${cells[1]} ${cells[2]} (${n} sites)`;
  }
  const side = Math.sqrt(n);
  if (/^(square|triangular)$/.test(inst.lattice) && Number.isInteger(side))
    return `${inst.lattice} ${side}x${side}`;
  return `${inst.lattice}, ${n} sites`;
}

export function instanceLabel(inst) {
  if (inst.model === "Impurity") return `${inst.lattice}, size ${inst.n_sites}`;
  const p = inst.params ?? {};
  const parts = [geometry(inst)];
  if (BOUNDARY[inst.boundary]) parts.push(BOUNDARY[inst.boundary]);
  for (const k of ["J2", "h", "U", "V"]) if (p[k] != null) parts.push(`${k} = ${p[k]}`);
  if (p.Nf != null) {
    // Filling per site. Hubbard files carry Nf = N_up = N_dn; t-V is spinless.
    const fill = (inst.model === "Hubbard" ? 2 * p.Nf : p.Nf) / inst.n_sites;
    const shown = Number(fill.toFixed(4));
    parts.push(`n ${shown === fill ? "=" : "&asymp;"} ${shown}`);
  }
  // VarBench does not document these Hamiltonian variants, so they are shown as named
  // rather than interpreted.
  for (const v of inst.instance_id.matchAll(/_(t12|UV1V2)(?=_|$)/g)) parts.push(v[1]);
  return parts.join(", ");
}

export function byGeometry(a, b) {
  const key = i => [i.lattice, i.n_sites, i.boundary ?? "", i.params?.Nf ?? 0,
    i.params?.J2 ?? i.params?.h ?? i.params?.U ?? i.params?.V ?? 0, i.instance_id];
  const ka = key(a), kb = key(b);
  for (let k = 0; k < ka.length; k++) {
    if (ka[k] === kb[k]) continue;
    return typeof ka[k] === "number" ? ka[k] - kb[k] : ka[k].localeCompare(kb[k]);
  }
  return 0;
}

// Why an instance has no record, in the words the table prints. The test order is
// summary.mjs's (noRecordKey), so the cells agree with the totals under the table.
const NO_RECORD = {
  no_sigma: "sampled rows carry no error bar",
  flagged: "every variational row is flagged",
  sector_only: "exact rows are sector-resolved, no ground-state energy stated",
  no_variational: "no variational row",
};
export function noRecordReason(inst) {
  return NO_RECORD[noRecordKey(inst)];
}

// The closest challenger: the lowest unflagged variational row above the record. On a
// solved instance that is the best variational bound anyone has published, and the
// number a new method has to beat to become the best variational one.
export function challengerOf(inst, rec) {
  const sorted = [...inst.rows].sort((a, b) => a.energy - b.energy);
  return sorted.slice(sorted.indexOf(rec) + 1).find(r => r.bound_type === "variational" && !r.defect) ?? null;
}

// How far above the record the challenger sits, per site, to two figures: "+1.7e-3".
// Relative to nothing, because the table is already per site in the papers' convention
// and that is the number a reader subtracts by hand. A gap under the record's quoted
// precision - DMRG converged to the exact energy at 1e-13 - is not a number the table
// stands behind, so it prints as below that precision rather than as twelve-digit noise.
export function gapAbove(rec, next, f, decimals) {
  const gap = (next.energy - rec.energy) / f;
  return gap < 10 ** -decimals ? `+<1e-${decimals}` : `+${gap.toExponential(1)}`;
}

const HEADER = ["| instance | record | method | closest challenger |", "|---|---|---|---|"];

function row(inst, label, cache) {
  const rec = recordOf(inst);
  if (!rec) return `| ${label} | no record | ${noRecordReason(inst)} | |`;
  const f = perSiteDivisor(inst) ?? 1;
  const q = quote(rec.energy / f, rec.sigma == null ? null : rec.sigma / f);
  const next = challengerOf(inst, rec);
  // Quoted at the record's precision so the two are readable against each other, with
  // the same markers the record cell uses and the gap above the record spelled out.
  // Each method carries its own source link, so the challenger is as checkable as the
  // record.
  const challenger = next
    ? `${(next.energy / f).toFixed(q.decimals)}${marks(next)} (${gapAbove(rec, next, f, q.decimals)}) ${shorten(next.method, 34)} ${citeCell(next, cache)}`
    : "none";
  return `| ${label} | **${q.text}**${marks(rec)} | ${shorten(rec.method, 46)} ${citeCell(rec, cache)} | ${challenger} |`;
}

function main() {
  const instances = collect();
  const s = summarize(instances);
  const cache = sources();

  const lines = [];
  lines.push(`### All ${s.instances} Hamiltonian instances (click to unravel)`);
  lines.push("");
  const known = new Set(MODELS.map(([m]) => m));
  for (const inst of instances)
    if (!known.has(inst.model)) throw new Error(`${inst.instance_id}: model ${inst.model} has no MODELS entry`);
  for (const [model, name] of MODELS) {
    const group = instances.filter(i => i.model === model).sort(byGeometry);
    if (!group.length) continue;
    // GitHub only renders a table inside <details> when a blank line follows <summary>.
    lines.push("<details>");
    lines.push(`<summary><b>${name}</b>: ${group.length} instances, energies as <code>${perSiteLabel(group[0])}</code></summary>`);
    lines.push("", ...HEADER, ...group.map(i => row(i, instanceLabel(i), cache)), "", "</details>", "");
  }

  // The legend (bound_type, bold, circle, dagger) and the table-wide counts are Tristan's
  // hand-written "## Details" section below the END marker since 2026-09-16 (2eb98a3), so
  // the generator emits nothing after the last </details>; the counts live in
  // data/_summary.json and on the site's front page.

  const readme = fs.readFileSync("README.md", "utf8");
  const i = readme.indexOf(BEGIN);
  const j = readme.indexOf(END);
  if (i < 0 || j < 0) throw new Error("README.md is missing the leaderboard markers");
  // Spliced by index, never by String.replace: a replacement containing $' or $& is
  // interpreted as a match reference and pastes the file back into itself.
  const block = `${BEGIN}\n\n${lines.join("\n").trimEnd()}\n\n${END}`;
  fs.writeFileSync("README.md", readme.slice(0, i) + block + readme.slice(j + END.length));
  console.log(`README.md leaderboard: ${s.instances} instances by model, ${s.records.held}/${s.instances} records held`);
}

// Side effect only when run directly, as in summary.mjs: site.mjs imports the labelling
// and quoting helpers above, and an import must never rewrite README.md as a surprise.
if (process.argv[1] && import.meta.url === `file://${path.resolve(process.argv[1])}`) main();
