// Generate STATS.md - the back pages of the leaderboard.
//
// These are the views that are interesting rather than authoritative: what nobody has
// contested, which records have stood longest, whether symmetrising actually wins, and
// how much a record costs in parameters. The front page stays the record book; this is
// where the curiosities live. Regenerated by build.sh, never hand-edited.
import fs from "node:fs";
import { perSiteDivisor, isSampled, recordEligible } from "./units.mjs";
import { collect, recordOf } from "./summary.mjs";
import { citeText, citeUrl } from "./cite.mjs";
import { sourceOf, sources } from "./enrich_sources.mjs";

const OUT = "STATS.md";
const cache = sources();
const instances = collect();
const L = [];
const p = (...s) => L.push(...s);

// A record on an instance nobody else has attempted says something very different from
// a record won against nine rivals. "Contested" is the cut used throughout this page.
const CONTESTED = 5;
const variationalRows = i => i.rows.filter(r => r.bound_type === "variational");

p("# QMBL — the back pages", "");
p("Generated by `scripts/stats.mjs` on every build. These views are for interest rather");
p("than adjudication: the record book is [README.md](README.md), and nothing here changes");
p("who holds a record. Where a view can only be computed over part of the table, it says so.", "");

// ---------------------------------------------------------------- uncontested records
p("## Records nobody has challenged", "");
// Largest first: an untested record on a 256-site frustrated lattice is a standing
// invitation, an untested one on a 14-site chain is a curiosity.
const uncontested = instances
  .map(i => ({ i, rec: recordOf(i), n: variationalRows(i).length }))
  .filter(x => x.rec && x.n === 1)
  .sort((a, b) => b.i.n_sites - a.i.n_sites);
p(`**${uncontested.length} of ${instances.filter(recordOf).length} records stand on a single published number.**`);
p("One group computed an energy, and in the years since, nobody has published a second");
p("one to compare it against. That is not a criticism of the number — it means the record");
p("is untested, and it is the cheapest possible target for anyone looking for one.", "");
p("| instance | record | method | source |");
p("|---|---|---|---|");
for (const { i, rec } of uncontested.slice(0, 15)) {
  const f = perSiteDivisor(i) ?? 1;
  const s = sourceOf(rec, cache);
  p(`| \`${i.instance_id}\` | ${(rec.energy / f).toFixed(7)} | ${rec.method.slice(0, 40)} | ${s ? `[${citeText(s)}](${citeUrl(s)})` : "no paper cited"} |`);
}
if (uncontested.length > 15) p(`\n…and ${uncontested.length - 15} more.`);
p("");

// ------------------------------------------------------------- symmetry projection
// Does enforcing the Hamiltonian's symmetries on the ansatz actually win? The table can
// answer that for itself, which is more interesting than any single paper's ablation.
const SYMM = /symmetr|projection|point.?group|spin.?parity|\bK\s*=\s*0\b|\bC4\b|translation|\bSU\(2\)\b|marshall/i;
p("## Records held: symmetrised vs not", "");
const contested = instances.filter(i => i.rows.length >= CONTESTED && recordOf(i));
const symTable = { all: { sym: 0, plain: 0 }, contested: { sym: 0, plain: 0 }, headToHead: { sym: 0, plain: 0 }, noRival: 0 };
for (const i of instances) {
  const rec = recordOf(i);
  if (!rec) continue;
  const isSym = SYMM.test(rec.method);
  symTable.all[isSym ? "sym" : "plain"]++;
  if (i.rows.length < CONTESTED) continue;
  symTable.contested[isSym ? "sym" : "plain"]++;
  // Head-to-head is the only column that isolates anything: both kinds of ansatz are
  // present on the instance, so the record was actually won against the other kind.
  const rows = variationalRows(i);
  if (rows.some(r => SYMM.test(r.method)) && rows.some(r => !SYMM.test(r.method)))
    symTable.headToHead[isSym ? "sym" : "plain"]++;
  else symTable.noRival++;
}
const h2h = symTable.headToHead.sym + symTable.headToHead.plain;
p("Does enforcing the Hamiltonian's own symmetries on the ansatz — momentum, point group,");
p("spin parity, SU(2), the Marshall sign — actually win records? The table can answer that");
p("for itself, which beats any single paper's ablation.", "");
p("| ansatz | records (all) | records (contested) | head-to-head |");
p("|---|---:|---:|---:|");
p(`| explicit symmetry projection | ${symTable.all.sym} | ${symTable.contested.sym} | ${symTable.headToHead.sym} |`);
p(`| no explicit projection | ${symTable.all.plain} | ${symTable.contested.plain} | ${symTable.headToHead.plain} |`);
p("");
p(`**Head-to-head is the column that means something**: ${h2h} instances have both kinds of ansatz`);
p("competing, so the record there was won against the other kind rather than by default.");
p(`It is currently **${symTable.headToHead.sym}–${symTable.headToHead.plain}** — a dead heat.`, "");
p("Read it as a hint rather than a result. Symmetrised ansätze are also, on average, the");
p("newer and more heavily optimised ones, so this does not isolate the projection itself.");
p("It does say that symmetrising is not the free win it is sometimes assumed to be.", "");

// --------------------------------------------------------------- oldest records
p("## The records that have stood longest", "");
const dated = instances
  .map(i => ({ i, rec: recordOf(i) }))
  .filter(x => x.rec)
  .map(x => ({ ...x, s: sourceOf(x.rec, cache) }))
  .filter(x => x.s?.year)
  .sort((a, b) => a.s.year - b.s.year);
const nDated = dated.length;
const nRec = instances.filter(recordOf).length;
p(`Computed over the **${nDated} of ${nRec} records whose source resolves to a year** — the rest cite a run`);
p("script with no paper, so they have no date to rank by.", "");
p("One line per paper — a single 2017 study holds seven impurity records, and listing them");
p("all would say more about that paper's scope than about how long records last.", "");
p("| year | oldest standing record | instance | records held by this paper |");
p("|---|---|---|---|");
const seenPaper = new Set();
for (const { i, rec, s } of dated) {
  if (seenPaper.has(s.key)) continue;
  seenPaper.add(s.key);
  const f = perSiteDivisor(i) ?? 1;
  const held = dated.filter(d => d.s.key === s.key).length;
  p(`| ${s.year} | [${citeText(s)}](${citeUrl(s)}) | \`${i.instance_id}\` (${(rec.energy / f).toFixed(7)}) | ${held} |`);
  if (seenPaper.size >= 12) break;
}
p("");
const byYear = {};
for (const { s } of dated) byYear[s.year] = (byYear[s.year] || 0) + 1;
p("Records by vintage:", "");
p("| year | records held |");
p("|---|---|");
for (const y of Object.keys(byYear).sort()) p(`| ${y} | ${"█".repeat(byYear[y])} ${byYear[y]} |`);
p("");

// ------------------------------------------------------------ parameter efficiency
// Several method strings carry an explicit parameter count. Where two ansatze on the
// same instance both report one, the comparison is the most useful thing on this page.
const PARAMS = /([\d.]+\s*[eE]\s*[+]?\d+|\d[\d,]{2,})\s*(?:variational\s*)?(?:params|pars|parameters)/i;
const paramCount = m => {
  const hit = (m || "").match(PARAMS);
  if (!hit) return null;
  const n = Number(hit[1].replace(/[,\s]/g, ""));
  return Number.isFinite(n) ? n : null;
};
p("## What a record costs in parameters", "");
const withParams = [];
for (const i of instances) {
  const rows = variationalRows(i).filter(r => paramCount(r.method) != null && recordEligible(r));
  if (rows.length < 2) continue;
  const f = perSiteDivisor(i) ?? 1;
  withParams.push({ i, f, rows: rows.sort((a, b) => a.energy - b.energy) });
}
if (!withParams.length) {
  p("No instance yet has two competing rows that both state a parameter count, so there is");
  p("nothing to compare. Parameter counts are parsed from the `method` string; stating one");
  p("in a submission is what puts a row here.", "");
} else {
  p(`**${withParams.length} instances** have two or more eligible rows that both state a parameter count.`);
  p("The cheapest ansatz within reach of the record is the interesting column.", "");
  p("| instance | energy | parameters | method |");
  p("|---|---|---|---|");
  for (const { i, f, rows } of withParams.slice(0, 6))
    for (const r of rows.slice(0, 4))
      p(`| \`${i.instance_id}\` | ${(r.energy / f).toFixed(7)} | ${paramCount(r.method).toExponential(1)} | ${r.method.slice(0, 38)} |`);
  p("");
}

// ------------------------------------------------------------------ ansatz families
// The headline number everyone wants, and the one most easily misread - so it is
// reported twice, and the gap between the two columns is the actual finding.
const FAMILIES = [
  ["tensor network", /\bdmrg\b|\bmps\b|\bpeps\b|tensor.?network|\bmera\b/i],
  ["transformer / ViT", /transformer|\bvit\b|attention|\bctwf\b/i],
  ["CNN / ResNet", /\bcnn\b|convnext|resnet|conv layer|\bace\b|\bscale\b/i],
  ["RNN", /\brnn\b/i],
  ["RBM", /\brbm\b/i],
  ["backflow / Pfaffian", /backflow|\bnnbf\b|pfaffian|\bhfps\b|hidden.?fermion/i],
  ["classic VMC", /gutzwiller|jastrow|\bbcs\b|spin liquid|\bmvmc\b|slater/i],
  ["AFQMC / GFMC", /afqmc|fixed.?node|\bgfmc\b|\bvafqmc\b/i],
  ["VQE / circuit", /\bvqe\b|circuit|statevector/i],
];
const family = m => FAMILIES.find(([, re]) => re.test(m || ""))?.[0] ?? "other";
const all = {}, hard = {};
for (const i of instances) {
  const rec = recordOf(i);
  if (!rec) continue;
  const fam = family(rec.method);
  all[fam] = (all[fam] || 0) + 1;
  if (i.rows.length >= CONTESTED) hard[fam] = (hard[fam] || 0) + 1;
}
p("## Records by ansatz family", "");
p("**Read the second column, not the first.** Counting every instance rewards whichever");
p("method was run on the most easy problems — 1D chains and small clusters, where the");
p("answer has been settled for a decade. The contested column counts only instances with");
p(`${CONTESTED}+ published rows, which is where the field is actually competing.`, "");
p("| family | records (all instances) | records (contested only) |");
p("|---|---:|---:|");
for (const [fam] of [...FAMILIES, ["other"]]) {
  if (!all[fam] && !hard[fam]) continue;
  p(`| ${fam} | ${all[fam] || 0} | ${hard[fam] || 0} |`);
}
p("");
p("Families are matched by regular expression against the `method` string, so read them");
p("as indicative. A row describing both an architecture and its optimiser lands in the");
p("first family that matches, in the order listed above.", "");

// ------------------------------------------------------------------------ countries
p("## Records held by country", "");
p("**This is the country of the first author's institution, which is not anyone's");
p("nationality** — a Chinese researcher at ETH counts here as Switzerland, and a paper");
p("with twelve authors across four countries counts once, for the first author.", "");
const cc = {}, byCountryInst = {};
let ccKnown = 0, ccNoPaper = 0, ccNoAffil = 0;
for (const i of instances) {
  const rec = recordOf(i);
  if (!rec) continue;
  const s = sourceOf(rec, cache);
  if (!s) { ccNoPaper++; continue; }
  const country = s.first_author_institution_country;
  if (!country) { ccNoAffil++; continue; }
  ccKnown++;
  cc[country] = (cc[country] || 0) + 1;
  if (s.first_author_institution)
    (byCountryInst[country] ||= new Set()).add(s.first_author_institution.split(",")[0].trim());
}
p(`Computed over **${ccKnown} of ${nRec} records**. Of the rest, ${ccNoPaper} cite a run script rather than a`);
p(`paper and have no author at all, and ${ccNoAffil} name a paper whose affiliation we could not resolve.`, "");
p("| country | records | first-author institutions |");
p("|---|---:|---|");
for (const [k, v] of Object.entries(cc).sort((a, b) => b[1] - a[1])) {
  const names = [...(byCountryInst[k] || [])].slice(0, 3).join("; ");
  p(`| ${k} | ${v} | ${names.slice(0, 70)}${names.length > 70 ? "…" : ""} |`);
}
p("");
p(`For the record, since someone will ask: **US ${cc.US || 0}, China ${cc.CN || 0}.** Resist reading a trend`);
p("into it. The counts are dominated by instances settled years ago, and the coverage gap");
p("above is not random — the unresolved sources skew heavily towards recent preprints,");
p("which is exactly where the newest groups publish first. What the table does show is");
p("that the current frontier records on 10×10, 16×16 and 20×20 J1-J2, and on 4×16 Hubbard,");
p("are held by groups at the Chinese Academy of Sciences and Peking University — and that");
p("none of those four appear in a by-country view built from bibliographic metadata alone,");
p("because none of those preprints carries an affiliation in it.", "");

p("---", "");
p("Affiliations come from OpenAlex where it has them, and otherwise from the author block");
p("of the paper itself via `scripts/affiliations_local.mjs`. Institution names are as the");
p("registries record them and are not deduplicated: OpenAlex splits the Flatiron Institute");
p("into two entities, one of which is a health-technology company.", "");

fs.writeFileSync(OUT, L.join("\n") + "\n");
console.log(`${OUT}: ${uncontested.length} uncontested, ${nDated}/${nRec} dated, ${withParams.length} param comparisons`);
