// Generate STATS.md - the back pages of the leaderboard.
//
// These are the views that are interesting rather than authoritative: what nobody has
// contested, which records have stood longest, whether symmetrising actually wins, and
// how much a record costs in parameters. The front page stays the record book; this is
// where the curiosities live. Regenerated by build.sh, never hand-edited.
import fs from "node:fs";
import { perSiteDivisor, isSampled, recordEligible } from "./units.mjs";
import { collect, recordOf } from "./summary.mjs";
import { citeText, citeUrl } from "./cite.mjs";
import { sourceOf, sources } from "./enrich_sources.mjs";

const OUT = "STATS.md";
const cache = sources();
const instances = collect();
const L = [];
const p = (...s) => L.push(...s);

// A record on an instance nobody else has attempted says something very different from
// a record won against nine rivals. "Contested" is the cut used throughout this page.
const CONTESTED = 5;
const variationalRows = i => i.rows.filter(r => r.bound_type === "variational");

p("# QMBL — the back pages", "");
p("Generated by `scripts/stats.mjs` on every build. These views are for interest rather");
p("than adjudication: the record book is [README.md](README.md), and nothing here changes");
p("who holds a record. Where a view can only be computed over part of the table, it says so.", "");

// ---------------------------------------------------------------- uncontested records
p("## Records nobody has challenged", "");
// Largest first: an untested record on a 256-site frustrated lattice is a standing
// invitation, an untested one on a 14-site chain is a curiosity.
const uncontested = instances
  .map(i => ({ i, rec: recordOf(i), n: variationalRows(i).length }))
  .filter(x => x.rec && x.n === 1)
  .sort((a, b) => b.i.n_sites - a.i.n_sites);
p(`**${uncontested.length} of ${instances.filter(recordOf).length} records stand on a single published number.**`);
p("One group computed an energy, and in the years since, nobody has published a second");
p("one to compare it against. That is not a criticism of the number — it is a statement");
p("about the coverage of this table, and of the literature it draws on.", "");
p("| instance | record | method | source |");
p("|---|---|---|---|");
for (const { i, rec } of uncontested.slice(0, 15)) {
  const f = perSiteDivisor(i) ?? 1;
  const s = sourceOf(rec, cache);
  p(`| \`${i.instance_id}\` | ${(rec.energy / f).toFixed(7)} | ${rec.method.slice(0, 40)} | ${s ? `[${citeText(s)}](${citeUrl(s)})` : "no paper cited"} |`);
}
if (uncontested.length > 15) p(`\n…and ${uncontested.length - 15} more.`);
p("");

// ------------------------------------------------------------- symmetry projection
// Does enforcing the Hamiltonian's symmetries on the ansatz actually win? The table can
// answer that for itself, which is more interesting than any single paper's ablation.
const SYMM = /symmetr|projection|point.?group|spin.?parity|\bK\s*=\s*0\b|\bC4\b|translation|\bSU\(2\)\b|marshall/i;
p("## Records held: symmetrised vs not", "");
const contested = instances.filter(i => i.rows.length >= CONTESTED && recordOf(i));
const symTable = { all: { sym: 0, plain: 0 }, contested: { sym: 0, plain: 0 }, headToHead: { sym: 0, plain: 0 }, noRival: 0 };
for (const i of instances) {
  const rec = recordOf(i);
  if (!rec) continue;
  const isSym = SYMM.test(rec.method);
  symTable.all[isSym ? "sym" : "plain"]++;
  if (i.rows.length < CONTESTED) continue;
  symTable.contested[isSym ? "sym" : "plain"]++;
  // The only column that isolates anything: both kinds of ansatz have been published on
  // this instance, so the record was taken with the alternative on the table. Not a
  // head-to-head - nobody ran a controlled comparison, the two kinds simply both exist
  // here, at different times, by different groups, at different levels of effort.
  const rows = variationalRows(i);
  if (rows.some(r => SYMM.test(r.method)) && rows.some(r => !SYMM.test(r.method)))
    symTable.headToHead[isSym ? "sym" : "plain"]++;
  else symTable.noRival++;
}
const h2h = symTable.headToHead.sym + symTable.headToHead.plain;
p("Does enforcing the Hamiltonian's own symmetries on the ansatz — momentum, point group,");
p("spin parity, SU(2), the Marshall sign — actually win records? The table can answer that");
p("for itself, which beats any single paper's ablation.", "");
p("| ansatz | records (all) | records (contested) | records where both kinds were tried |");
p("|---|---:|---:|---:|");
p(`| explicit symmetry projection | ${symTable.all.sym} | ${symTable.contested.sym} | ${symTable.headToHead.sym} |`);
p(`| no explicit projection | ${symTable.all.plain} | ${symTable.contested.plain} | ${symTable.headToHead.plain} |`);
p("");
p(`**The last column is the one that means anything**: on ${h2h} instances both a symmetrised and an`);
p("unsymmetrised ansatz have been published, so the record was taken with the alternative");
p(`already on the table. It stands at **${symTable.headToHead.sym}–${symTable.headToHead.plain}**.`, "");
p("It is deliberately *not* called a head-to-head, because nothing here is a controlled");
p("comparison: the two kinds were run at different times, by different groups, at wildly");
p("different levels of effort, and often on different hardware. Symmetrised ansätze also");
p("tend to be the newer and more heavily optimised ones. So read an even split as evidence");
p("that symmetrising is not the free win it is sometimes assumed to be — not as a measured");
p("effect size for the projection itself.", "");

// --------------------------------------------------------------- oldest records
p("## The records that have stood longest", "");
const dated = instances
  .map(i => ({ i, rec: recordOf(i) }))
  .filter(x => x.rec)
  .map(x => ({ ...x, s: sourceOf(x.rec, cache) }))
  .filter(x => x.s?.year)
  .sort((a, b) => a.s.year - b.s.year);
const nDated = dated.length;
const nRec = instances.filter(recordOf).length;
p(`Computed over the **${nDated} of ${nRec} records whose source resolves to a year** — the rest cite a run`);
p("script with no paper, so they have no date to rank by.", "");
p("One line per paper — a single 2017 study holds seven impurity records, and listing them");
p("all would say more about that paper's scope than about how long records last.", "");
p("| year | oldest standing record | instance | records held by this paper |");
p("|---|---|---|---|");
const seenPaper = new Set();
for (const { i, rec, s } of dated) {
  if (seenPaper.has(s.key)) continue;
  seenPaper.add(s.key);
  const f = perSiteDivisor(i) ?? 1;
  const held = dated.filter(d => d.s.key === s.key).length;
  p(`| ${s.year} | [${citeText(s)}](${citeUrl(s)}) | \`${i.instance_id}\` (${(rec.energy / f).toFixed(7)}) | ${held} |`);
  if (seenPaper.size >= 12) break;
}
p("");
const byYear = {};
for (const { s } of dated) byYear[s.year] = (byYear[s.year] || 0) + 1;
p("Records by vintage:", "");
p("| year | records held |");
p("|---|---|");
for (const y of Object.keys(byYear).sort()) p(`| ${y} | ${"█".repeat(byYear[y])} ${byYear[y]} |`);
p("");

// ------------------------------------------------------------ parameter efficiency
// Several method strings carry an explicit parameter count. Where two ansatze on the
// same instance both report one, the comparison is the most useful thing on this page.
const PARAMS = /([\d.]+\s*[eE]\s*[+]?\d+|\d[\d,]{2,})\s*(?:variational\s*)?(?:params|pars|parameters)/i;
const paramCount = m => {
  const hit = (m || "").match(PARAMS);
  if (!hit) return null;
  const n = Number(hit[1].replace(/[,\s]/g, ""));
  return Number.isFinite(n) ? n : null;
};
p("## What a record costs in parameters", "");
const withParams = [];
for (const i of instances) {
  const rows = variationalRows(i).filter(r => paramCount(r.method) != null && recordEligible(r));
  if (rows.length < 2) continue;
  const f = perSiteDivisor(i) ?? 1;
  withParams.push({ i, f, rows: rows.sort((a, b) => a.energy - b.energy) });
}
if (!withParams.length) {
  p("No instance yet has two competing rows that both state a parameter count, so there is");
  p("nothing to compare. Parameter counts are parsed from the `method` string; stating one");
  p("in a submission is what puts a row here.", "");
} else {
  p(`**${withParams.length} instances** have two or more eligible rows that both state a parameter count.`);
  p("The cheapest ansatz within reach of the record is the interesting column.", "");
  p("| instance | energy | parameters | method |");
  p("|---|---|---|---|");
  for (const { i, f, rows } of withParams.slice(0, 6))
    for (const r of rows.slice(0, 4))
      p(`| \`${i.instance_id}\` | ${(r.energy / f).toFixed(7)} | ${paramCount(r.method).toExponential(1)} | ${r.method.slice(0, 38)} |`);
  p("");
}

// ------------------------------------------------------------------ ansatz families
// The headline number everyone wants, and the one most easily misread - so it is
// reported twice, and the gap between the two columns is the actual finding.
const FAMILIES = [
  ["tensor network", /\bdmrg\b|\bmps\b|\bpeps\b|tensor.?network|\bmera\b/i],
  ["transformer / ViT", /transformer|\bvit\b|attention|\bctwf\b/i],
  ["CNN / ResNet", /\bcnn\b|convnext|resnet|conv layer|\bace\b|\bscale\b/i],
  ["RNN", /\brnn\b/i],
  ["RBM", /\brbm\b/i],
  ["backflow / Pfaffian", /backflow|\bnnbf\b|pfaffian|\bhfps\b|hidden.?fermion/i],
  ["classic VMC", /gutzwiller|jastrow|\bbcs\b|spin liquid|\bmvmc\b|slater/i],
  ["AFQMC / GFMC", /afqmc|fixed.?node|\bgfmc\b|\bvafqmc\b/i],
  ["VQE / circuit", /\bvqe\b|circuit|statevector/i],
];
const family = m => FAMILIES.find(([, re]) => re.test(m || ""))?.[0] ?? "other";
const all = {}, hard = {};
for (const i of instances) {
  const rec = recordOf(i);
  if (!rec) continue;
  const fam = family(rec.method);
  all[fam] = (all[fam] || 0) + 1;
  if (i.rows.length >= CONTESTED) hard[fam] = (hard[fam] || 0) + 1;
}
p("## Records by ansatz family", "");
p("**Read the second column, not the first.** Counting every instance rewards whichever");
p("method was run on the most easy problems — 1D chains and small clusters, where the");
p("answer has been settled for a decade. The contested column counts only instances with");
p(`${CONTESTED}+ published rows, which is where the field is actually competing.`, "");
p("| family | records (all instances) | records (contested only) |");
p("|---|---:|---:|");
for (const [fam] of [...FAMILIES, ["other"]]) {
  if (!all[fam] && !hard[fam]) continue;
  p(`| ${fam} | ${all[fam] || 0} | ${hard[fam] || 0} |`);
}
p("");
p("Families are matched by regular expression against the `method` string, so read them");
p("as indicative. A row describing both an architecture and its optimiser lands in the");
p("first family that matches, in the order listed above.", "");

// ------------------------------------------------------------------------ countries
p("## Records held by country", "");
p("**This is the country of the first author's institution, which is not anyone's");
p("nationality** — a Chinese researcher at ETH counts here as Switzerland, and a paper");
p("with twelve authors across four countries counts once, for the first author.", "");
// Rows whose only reference is a varbench/methods run script are not unattributed: the
// number was produced by the VarBench collaboration and its citable source is the
// Science paper. But that paper has 33 authors across 8 countries, so filing all of
// them under its first author's institution would put ~half the table in one country
// on the strength of an author-list ordering. They get their own line instead.
const isVarbenchBaseline = r => r.baseline === true;
const cc = {}, byCountryInst = {};
let ccKnown = 0, ccBaseline = 0, ccNoAffil = 0;
for (const i of instances) {
  const rec = recordOf(i);
  if (!rec) continue;
  const s = sourceOf(rec, cache);
  if (!s) { if (isVarbenchBaseline(rec)) ccBaseline++; else ccNoAffil++; continue; }
  const country = s.first_author_institution_country;
  if (!country) { ccNoAffil++; continue; }
  ccKnown++;
  cc[country] = (cc[country] || 0) + 1;
  if (s.first_author_institution)
    (byCountryInst[country] ||= new Set()).add(s.first_author_institution.split(",")[0].trim());
}
const independent = ccKnown + ccNoAffil;
p(`Of the ${nRec} records, **${ccBaseline} are VarBench's own baseline runs** — their only reference is a`);
p("run script in `varbench/methods`, so the number came from the benchmark collaboration");
p("rather than from an independent paper. Those are excluded below and counted separately:");
p("the [VarBench paper](https://doi.org/10.1126/science.adg9774) has 33 authors across 8 countries, and filing all of them under");
p("its first author's institution would put half this table in one country on the strength");
p("of an author-list ordering.", "");
p(`That leaves **${independent} records from independent papers, of which ${ccKnown} resolve to a country** and`);
p(`${ccNoAffil} do not.`, "");
p("| country | records | first-author institutions |");
p("|---|---:|---|");
for (const [k, v] of Object.entries(cc).sort((a, b) => b[1] - a[1])) {
  const names = [...(byCountryInst[k] || [])].slice(0, 3).join("; ");
  p(`| ${k} | ${v} | ${names.slice(0, 70)}${names.length > 70 ? "…" : ""} |`);
}
// Same table, no blank line: a gap here ends the table and leaves this row as stray text.
p(`| *VarBench collaboration* | *${ccBaseline}* | *33 authors, 8 countries — not attributed to one* |`);
p("");
p("Two things the table does not say. **It is not a ranking of who is ahead**: a record set");
p("in 2017 and one taken last month weigh the same, and a country total says nothing about");
p("*which* instances are held — the four frontier records in the README are held by two");
p("groups, which is invisible in a column of totals. **And it is not a measure of output**:");
p("it counts records currently standing, so a group whose results have since been beaten");
p("disappears from it entirely.", "");
p("It is also only as good as the affiliation data. Every preprint holding a frontier record");
p("carries no affiliation in any bibliographic database; those rows are in the table only");
p("because `scripts/affiliations_local.mjs` reads the affiliation off the paper itself.", "");

p("---", "");
p("Affiliations come from OpenAlex where it has them, and otherwise from the author block");
p("of the paper itself via `scripts/affiliations_local.mjs`. Institution names are as the");
p("registries record them and are not deduplicated: OpenAlex splits the Flatiron Institute");
p("into two entities, one of which is a health-technology company.", "");

fs.writeFileSync(OUT, L.join("\n") + "\n");
console.log(`${OUT}: ${uncontested.length} uncontested, ${nDated}/${nRec} dated, ${withParams.length} param comparisons`);
